name: lego
description: "lego is all you need"
#publish_to: 'none'
#repository: https://github.com/melodysdreamj/lego

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  june_flow_util:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true