name: lego_cli
description: "lego cli"
version: 0.9.17
homepage: https://github.com/melodysdreamj/lego/tree/lego_cli

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  args: ^2.5.0
  flutter:
    sdk: flutter
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

executables:
  lego: lego_cli